name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.4, 8.3, 8.2, 8.1]
                laravel: [11.*, 10.*]
                dependency-version: [prefer-stable]
                exclude:
                    -   php: 8.1
                        laravel: 11.*
                    -   php: 8.4
                        laravel: 10.*


        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer update --${{ matrix.dependency-version }} --with="laravel/framework:${{ matrix.laravel }}" --prefer-dist --no-interaction --no-suggest
                env:
                    COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

            -   name: Execute tests
                run: vendor/bin/phpunit
